-- =============================================================================
-- AUTH EMAIL
-- =============================================================================
-- Active: EmailJS OTP → emailjs-registration-otp.html
-- Inactive while Confirm email is OFF: confirm-signup.html (Supabase Auth)
-- =============================================================================
